### ISSUE TITLE
windows paths?

### ISSUE THREAD

**Issue by mcharytoniuk** [mk-pmb/common-urlpath-prefix-js#1]
Thanks for this great npm package! :)

Does common-urlpath-prefix support Windows paths? Did you consider using https://www.npmjs.com/package/upath for path normalization?

**Comment by mk-pmb** [comment]
You're welcome!

Since the focus is on URLs, there's no explicit support for Windows paths. Maybe a backslash as custom separator can help, though. I added [examples of how backslashes turn out](https://github.com/mk-pmb/common-urlpath-prefix-js/commit/dac1e481e356006c62da5f3870f22d880bceeb2a?diff=unified), and clarification that [paths are not resolved](https://github.com/mk-pmb/common-urlpath-prefix-js/commit/cdd874c452c9ce71d348231127edc1cd516edfd1?diff=unified). (The latter might become an option someday.)

Normalization with `upath` to me looks out of scope for a package that deals with URL paths.

**Comment by mk-pmb** [comment]
New in 0.2.2: You can pre-configure your custom options. Backslash example included. :-)
